networks:
  template_app:

volumes:
  mariadb:

name: template-flask-dev

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: template-flask-app-dev
    container_name: template-flask-app
    hostname: ${DEV_HOSTNAME}
    command: python3 template_app.py
    depends_on:
      - mariadb
    stop_signal: SIGINT
    # to sync the ./api dir with the container only for development
    volumes:
      - ./app:/home/app/app
      - ./migrations:/home/app/migrations
    env_file:
      - template-app.env
    healthcheck:
      test: curl --fail http://localhost:5000 -H 'Host:localhost' || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      template_app:
        aliases:
          - template_flask_app
    restart: always

  nginx:
    build: nginx
    ports:
      - 5010:80
    depends_on:
      - app
    networks:
      template_app:
    restart: always

  mariadb:
    image: mariadb:11
    env_file:
      - template-app.env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      template_app:
