networks:
  template_app:

volumes:
  mariadb:

name: template-flask-dev

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: template-flask-app-dev
    container_name: template-flask-app
    hostname: ${DEV_HOSTNAME}
    command: python3 template_app.py
    depends_on:
      - mariadb
    stop_signal: SIGINT
    # to sync the ./api dir with the container only for development
    volumes:
      - ./app:/home/app/app
      - ./migrations:/home/app/migrations
    environment:
      - FLASK_APP=template_app.py
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://${MARIADB_USER}:${MARIADB_PASSWORD}@mariadb:3306/${MARIADB_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - APP_SETTINGS=config.DevelopmentConfig
      - HOSTNAME=${DEV_HOSTNAME}
      - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      - MAINTENANCE_MODE=False
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    healthcheck:
      test: curl --fail http://${DEV_HOSTNAME}:5000 -H 'Host:${DEV_HOSTNAME}' || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      template_app:
        aliases:
          - template_flask_app
    restart: always

  nginx:
    build: nginx
    ports:
      - 5010:80
    depends_on:
      - app
    networks:
      template_app:
    restart: always

  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      template_app:
