networks:
  template_app:
  default:
    external: true
    name: proxy

volumes:
  mariadb:

name: template-app

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: template-flask-app
    container_name: template_flask_app-prod
    entrypoint: ['./boot.sh']
    depends_on:
      - mariadb
    stop_signal: SIGINT
    # to sync the ./api dir with the container only for development
    volumes:
      - ./logs/app:/home/app/logs
      - ./migrations:/home/app/migrations
    env_file:
      - template-app.env
    environment:
      - APP_SETTINGS=config.ProductionConfig
    healthcheck:
      test: curl --fail http://localhost:5000 -H 'Host:localhost' || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      template_app:
        aliases:
          - template_app
    restart: unless-stopped

  nginx:
    build: nginx
    ports:
      - 5010:80
    depends_on:
      - app
    networks:
      template_app:
      default:
    restart: unless-stopped

  mariadb:
    image: mariadb:11
    env_file:
      - template-app.env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      template_app: