"""add on delete cascaed to preprocessing jobs

Revision ID: 02ada276f374
Revises: 9e4618e3a165
Create Date: 2025-10-04 19:19:42.660967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ada276f374'
down_revision = '9e4618e3a165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocessing_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_preprocessing_jobs_new_uploaded_file_id_uploaded_files'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_preprocessing_jobs_uploaded_file_id_uploaded_files'), 'uploaded_files', ['uploaded_file_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocessing_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_preprocessing_jobs_uploaded_file_id_uploaded_files'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_preprocessing_jobs_new_uploaded_file_id_uploaded_files'), 'uploaded_files', ['uploaded_file_id'], ['id'])

    # ### end Alembic commands ###
