"""remove confirmed column because handled by fs

Revision ID: 112af16d2442
Revises: b886665b1dc3
Create Date: 2025-07-10 15:46:43.678975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112af16d2442'
down_revision = 'b886665b1dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
