"""Add CombinedPreprocessingJob model for merging preprocessed datasets

Revision ID: 24e363bf8a97
Revises: 3ee2ed9a56e3
Create Date: 2025-08-25 14:22:43.964082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e363bf8a97'
down_revision = '3ee2ed9a56e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combined_preprocessing_jobs',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('first_job_id', sa.String(length=36), nullable=False),
    sa.Column('second_job_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('edges_file', sa.String(length=500), nullable=True),
    sa.Column('nodes_file', sa.String(length=500), nullable=True),
    sa.Column('total_nodes', sa.Integer(), nullable=True),
    sa.Column('total_edges', sa.Integer(), nullable=True),
    sa.Column('nodes_from_first', sa.Integer(), nullable=True),
    sa.Column('nodes_from_second', sa.Integer(), nullable=True),
    sa.Column('new_nodes', sa.Integer(), nullable=True),
    sa.Column('first_start_date', sa.DateTime(), nullable=True),
    sa.Column('first_end_date', sa.DateTime(), nullable=True),
    sa.Column('second_start_date', sa.DateTime(), nullable=True),
    sa.Column('second_end_date', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_job_id'], ['preprocessing_jobs.uuid'], name=op.f('fk_combined_preprocessing_jobs_first_job_id_preprocessing_jobs')),
    sa.ForeignKeyConstraint(['second_job_id'], ['preprocessing_jobs.uuid'], name=op.f('fk_combined_preprocessing_jobs_second_job_id_preprocessing_jobs')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_combined_preprocessing_jobs_user_id_user')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_combined_preprocessing_jobs')),
    sa.UniqueConstraint('task_id', name=op.f('uq_combined_preprocessing_jobs_task_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combined_preprocessing_jobs')
    # ### end Alembic commands ###
