"""remove payments table

Revision ID: 33e2f4f9a45d
Revises: 796888740542
Create Date: 2025-10-04 19:04:38.448611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e2f4f9a45d'
down_revision = '796888740542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('stripe_payment_id', sa.VARCHAR(length=150), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('stripe_customer_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('stripe_customer_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('stripe_customer_address_country', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_payments_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('stripe_payment_id', name=op.f('uq_payments_stripe_payment_id'))
    )
    # ### end Alembic commands ###
