"""use id, username, email and password from flask security

Revision ID: 343670950c0f
Revises: a480cc2dda67
Create Date: 2025-03-26 15:53:28.437617

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "343670950c0f"
down_revision = "a480cc2dda67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "username",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=255),
            nullable=True,
        )
        batch_op.alter_column(
            "email",
            existing_type=sa.VARCHAR(length=120),
            type_=sa.String(length=255),
            existing_nullable=False,
        )
        batch_op.drop_index("ix_user_email")
        batch_op.drop_index("ix_user_username")
        batch_op.create_unique_constraint("unique_email", ["email"])
        batch_op.create_unique_constraint("unique_username", ["username"])
        batch_op.drop_column("password_hash")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_hash", sa.VARCHAR(length=256), nullable=True)
        )
        batch_op.drop_constraint("unique_email", type_="unique")
        batch_op.drop_constraint("unique_username", type_="unique")
        batch_op.create_index("ix_user_username", ["username"], unique=1)
        batch_op.create_index("ix_user_email", ["email"], unique=1)
        batch_op.alter_column(
            "email",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=120),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "username",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=64),
            nullable=False,
        )

    # ### end Alembic commands ###
