"""add on delete cascade to delete user

Revision ID: 3526b4c1d6e5
Revises: e2737709934a
Create Date: 2025-10-09 14:43:06.962314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3526b4c1d6e5'
down_revision = 'e2737709934a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_enrichment_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_playlist_enrichment_jobs_preprocessing_job_id_prepro_db47'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_playlist_enrichment_jobs_preprocessing_job_id_preprocessing_jobs'), 'preprocessing_jobs', ['preprocessing_job_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_uploaded_files_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_uploaded_files_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_uploaded_files_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_uploaded_files_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('playlist_enrichment_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_playlist_enrichment_jobs_preprocessing_job_id_preprocessing_jobs'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_playlist_enrichment_jobs_preprocessing_job_id_prepro_db47'), 'preprocessing_jobs', ['preprocessing_job_id'], ['uuid'])

    # ### end Alembic commands ###
