"""Add PlaylistEnrichmentJob model

Revision ID: 3ee2ed9a56e3
Revises: cd6a4ccfcbb5
Create Date: 2025-08-07 16:18:32.261570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee2ed9a56e3'
down_revision = 'cd6a4ccfcbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_enrichment_jobs',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('preprocessing_job_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('output_file', sa.String(length=500), nullable=True),
    sa.Column('total_playlists', sa.Integer(), nullable=True),
    sa.Column('found_count', sa.Integer(), nullable=True),
    sa.Column('not_found_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['preprocessing_job_id'], ['preprocessing_jobs.uuid'], name=op.f('fk_playlist_enrichment_jobs_preprocessing_job_id_preprocessing_jobs')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_playlist_enrichment_jobs')),
    sa.UniqueConstraint('task_id', name=op.f('uq_playlist_enrichment_jobs_task_id'))
    )
    with op.batch_alter_table('preprocessing_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_preprocessing_jobs_new_task_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_preprocessing_jobs_task_id'), ['task_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocessing_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_preprocessing_jobs_task_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_preprocessing_jobs_new_task_id'), ['task_id'])

    op.drop_table('playlist_enrichment_jobs')
    # ### end Alembic commands ###
