"""Add UploadedFile and PreprocessingJob models

Revision ID: 448558f5b342
Revises: b4012e3fe836
Create Date: 2025-08-01 19:38:31.143651

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "448558f5b342"
down_revision = "b4012e3fe836"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploaded_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_uploaded_files_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploaded_files")),
        sa.UniqueConstraint("filename", name=op.f("uq_uploaded_files_filename")),
    )
    op.create_table(
        "preprocessing_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=False),
        sa.Column("uploaded_file_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("edges_file", sa.String(length=500), nullable=True),
        sa.Column("nodes_file", sa.String(length=500), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["uploaded_file_id"],
            ["uploaded_files.id"],
            name=op.f("fk_preprocessing_jobs_uploaded_file_id_uploaded_files"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preprocessing_jobs")),
        sa.UniqueConstraint("task_id", name=op.f("uq_preprocessing_jobs_task_id")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("preprocessing_jobs")
    op.drop_table("uploaded_files")
    # ### end Alembic commands ###
