"""Add data_start_date and data_end_date to UploadedFile

Revision ID: 46e77fd6dc35
Revises: 24e363bf8a97
Create Date: 2025-08-25 15:05:14.300700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e77fd6dc35'
down_revision = '24e363bf8a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('data_end_date')
        batch_op.drop_column('data_start_date')

    # ### end Alembic commands ###
