"""remove uploaded at since it is in TimeStamp Mixin

Revision ID: 61aefbc04a73
Revises: 02ada276f374
Create Date: 2025-10-04 19:48:09.381978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61aefbc04a73'
down_revision = '02ada276f374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('uploaded_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
