"""Add published fields to jobs

Revision ID: 71da8a3b2cec
Revises: bff9f3199e21
Create Date: 2025-10-04 21:00:26.778413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71da8a3b2cec'
down_revision = 'bff9f3199e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combined_preprocessing_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('preprocessing_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocessing_jobs', schema=None) as batch_op:
        batch_op.drop_column('published_at')
        batch_op.drop_column('published')

    with op.batch_alter_table('combined_preprocessing_jobs', schema=None) as batch_op:
        batch_op.drop_column('published_at')
        batch_op.drop_column('published')

    # ### end Alembic commands ###
