"""drop filename and original_filename for name column

Revision ID: 796888740542
Revises: 38bb912ca62e
Create Date: 2025-10-04 16:09:26.750834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796888740542'
down_revision = '38bb912ca62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_uploaded_files_filename'), type_='unique')
        batch_op.drop_column('filename')
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=255), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_uploaded_files_filename'), ['filename'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
