"""add on delete cascade to delete user accounts

Revision ID: 9ceb6a3b3fcd
Revises: 46e77fd6dc35
Create Date: 2025-10-04 11:55:13.154322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ceb6a3b3fcd'
down_revision = '46e77fd6dc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_friend_request_sender_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_friend_request_receiver_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_friend_request_receiver_id_user'), 'user', ['receiver_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_friend_request_sender_id_user'), 'user', ['sender_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_payments_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_payments_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('friend_request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_friend_request_sender_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_friend_request_receiver_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_friend_request_receiver_id_user'), 'user', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_friend_request_sender_id_user'), 'user', ['sender_id'], ['id'])

    # ### end Alembic commands ###
