"""use back_populates instead of backref

Revision ID: 9e4618e3a165
Revises: 33e2f4f9a45d
Create Date: 2025-10-04 19:15:08.595249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4618e3a165'
down_revision = '33e2f4f9a45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_combined_preprocessing_jobs')
    with op.batch_alter_table('combined_preprocessing_jobs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_combined_preprocessing_jobs_second_job_id_preprocessing_jobs'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_combined_preprocessing_jobs_first_job_id_preprocessing_jobs'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_combined_preprocessing_jobs_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_combined_preprocessing_jobs_first_job_id_preprocessing_jobs'), 'preprocessing_jobs', ['first_job_id'], ['uuid'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_combined_preprocessing_jobs_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_combined_preprocessing_jobs_second_job_id_preprocessing_jobs'), 'preprocessing_jobs', ['second_job_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('combined_preprocessing_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_combined_preprocessing_jobs_second_job_id_preprocessing_jobs'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_combined_preprocessing_jobs_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_combined_preprocessing_jobs_first_job_id_preprocessing_jobs'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_combined_preprocessing_jobs_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_combined_preprocessing_jobs_first_job_id_preprocessing_jobs'), 'preprocessing_jobs', ['first_job_id'], ['uuid'])
        batch_op.create_foreign_key(batch_op.f('fk_combined_preprocessing_jobs_second_job_id_preprocessing_jobs'), 'preprocessing_jobs', ['second_job_id'], ['uuid'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_combined_preprocessing_jobs',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('first_job_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('second_job_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('edges_file', sa.VARCHAR(length=500), nullable=True),
    sa.Column('nodes_file', sa.VARCHAR(length=500), nullable=True),
    sa.Column('total_nodes', sa.INTEGER(), nullable=True),
    sa.Column('total_edges', sa.INTEGER(), nullable=True),
    sa.Column('nodes_from_first', sa.INTEGER(), nullable=True),
    sa.Column('nodes_from_second', sa.INTEGER(), nullable=True),
    sa.Column('new_nodes', sa.INTEGER(), nullable=True),
    sa.Column('first_start_date', sa.DATETIME(), nullable=True),
    sa.Column('first_end_date', sa.DATETIME(), nullable=True),
    sa.Column('second_start_date', sa.DATETIME(), nullable=True),
    sa.Column('second_end_date', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['first_job_id'], ['preprocessing_jobs.uuid'], name=op.f('fk_combined_preprocessing_jobs_first_job_id_preprocessing_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_job_id'], ['preprocessing_jobs.uuid'], name=op.f('fk_combined_preprocessing_jobs_second_job_id_preprocessing_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_combined_preprocessing_jobs_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_combined_preprocessing_jobs')),
    sa.UniqueConstraint('task_id', name=op.f('uq_combined_preprocessing_jobs_task_id'))
    )
    # ### end Alembic commands ###
