"""add flask security user

Revision ID: a480cc2dda67
Revises: bbee5b3c3b72
Create Date: 2025-03-26 15:40:05.841319

"""

from alembic import op
import sqlalchemy as sa
import flask_security


# revision identifiers, used by Alembic.
revision = "a480cc2dda67"
down_revision = "bbee5b3c3b72"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("permissions", flask_security.datastore.AsaList(), nullable=True),
        sa.Column(
            "update_datetime",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "roles_users",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("fs_webauthn_user_handle", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "mf_recovery_codes", flask_security.datastore.AsaList(), nullable=True
            )
        )
        batch_op.add_column(sa.Column("password", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column("us_phone_number", sa.String(length=128), nullable=True)
        )
        batch_op.add_column(sa.Column("us_totp_secrets", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("active", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column("fs_uniquifier", sa.String(length=64), nullable=False)
        )
        batch_op.add_column(sa.Column("confirmed_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("last_login_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("current_login_at", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column("last_login_ip", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("current_login_ip", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(sa.Column("login_count", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("tf_primary_method", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("tf_totp_secret", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("tf_phone_number", sa.String(length=128), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "create_datetime",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "update_datetime",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.create_unique_constraint("unique us phone number", ["us_phone_number"])
        batch_op.create_unique_constraint(
            "unique webauth user handle", ["fs_webauthn_user_handle"]
        )
        batch_op.create_unique_constraint("unique uniquifier", ["fs_uniquifier"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("unique us phone number", type_="unique")
        batch_op.drop_constraint("unique webauth user handle", type_="unique")
        batch_op.drop_constraint("unique uniquifier", type_="unique")
        batch_op.drop_column("update_datetime")
        batch_op.drop_column("create_datetime")
        batch_op.drop_column("tf_phone_number")
        batch_op.drop_column("tf_totp_secret")
        batch_op.drop_column("tf_primary_method")
        batch_op.drop_column("login_count")
        batch_op.drop_column("current_login_ip")
        batch_op.drop_column("last_login_ip")
        batch_op.drop_column("current_login_at")
        batch_op.drop_column("last_login_at")
        batch_op.drop_column("confirmed_at")
        batch_op.drop_column("fs_uniquifier")
        batch_op.drop_column("active")
        batch_op.drop_column("us_totp_secrets")
        batch_op.drop_column("us_phone_number")
        batch_op.drop_column("password")
        batch_op.drop_column("mf_recovery_codes")
        batch_op.drop_column("fs_webauthn_user_handle")

    op.drop_table("roles_users")
    op.drop_table("role")
    # ### end Alembic commands ###
