"""add consistend constraint names'


Revision ID: b886665b1dc3
Revises: 343670950c0f
Create Date: 2025-04-05 12:19:13.292551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b886665b1dc3'
down_revision = '343670950c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_payments_stripe_payment_id'), ['stripe_payment_id'])

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_role_name'), ['name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique uniquifier', type_='unique')
        batch_op.drop_constraint('unique us phone number', type_='unique')
        batch_op.drop_constraint('unique webauth user handle', type_='unique')
        batch_op.drop_constraint('unique_email', type_='unique')
        batch_op.drop_constraint('unique_username', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_fs_uniquifier'), ['fs_uniquifier'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_fs_webauthn_user_handle'), ['fs_webauthn_user_handle'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_us_phone_number'), ['us_phone_number'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_us_phone_number'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_fs_webauthn_user_handle'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_fs_uniquifier'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.create_unique_constraint('unique_username', ['username'])
        batch_op.create_unique_constraint('unique_email', ['email'])
        batch_op.create_unique_constraint('unique webauth user handle', ['fs_webauthn_user_handle'])
        batch_op.create_unique_constraint('unique us phone number', ['us_phone_number'])
        batch_op.create_unique_constraint('unique uniquifier', ['fs_uniquifier'])

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_role_name'), type_='unique')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_payments_stripe_payment_id'), type_='unique')

    # ### end Alembic commands ###
