"""add uuid to uploaded files

Revision ID: c0b52c287e97
Revises: 9ceb6a3b3fcd
Create Date: 2025-10-04 13:38:46.679815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b52c287e97'
down_revision = '9ceb6a3b3fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_uploaded_files_uuid'), ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_uploaded_files_uuid'), type_='unique')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
