"""Add graph statistics fields to PreprocessingJob

Revision ID: d09e626e499a
Revises: 448558f5b342
Create Date: 2025-08-01 19:54:13.456521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09e626e499a'
down_revision = '448558f5b342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocessing_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_nodes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('final_edges', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_periods', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocessing_jobs', schema=None) as batch_op:
        batch_op.drop_column('time_periods')
        batch_op.drop_column('final_edges')
        batch_op.drop_column('final_nodes')

    # ### end Alembic commands ###
