"""task_id can be null on prepocessing task

Revision ID: e2737709934a
Revises: b851e956f290
Create Date: 2025-10-09 11:09:31.762234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2737709934a'
down_revision = 'b851e956f290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocessing_jobs', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocessing_jobs', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
